### PR TITLE
move the call of X.data inside the method

### PR DESCRIPTION
**Pull request by KirillZubov**
issue https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl/issues/29

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Why should these not be tracked?

**Comment by KirillZubov** [comment]
> Why should these not be tracked?
X doesn't need tracked градиент but if pass tracked X in μ(X, p, t), we get an error. Really, just a call of x.data was moved inside the method. I didn't change the method behavior.

**Comment by ChrisRackauckas** [comment]
Why would that give the right gradient?

**Comment by KirillZubov** [comment]
> Why would that give the right gradient?

X is points. We don't need the gradient of points to calculate backpropagation.

**Comment by ChrisRackauckas** [comment]
oh yes, `X` can be considered a random constant.

**Pull request merged**
